save_file_version="RT001"
supported_file_versions= ["RT001"]
current_room_leader = "Current room: "    
default_save_file = "zorkSave"
save_file_ext= ".sav"
current_room_leader = "Current room: " 
top_level_delimiter = "==="
second_level_delim = "---"
rooms_marker = "Rooms:"
exits_marker = "Exits:"
file_name_leader = "Dungeon file: "
room_states_marker = "Room states:"